mod 'boxen', '2.1.0', :github_tarball      => 'boxen/puppet-boxen'
mod 'stdlib', '4.0.0', :github_tarball     => 'puppetlabs/puppetlabs-stdlib'
mod 'homebrew', '1.2.1', :github_tarball   => 'boxen/puppet-homebrew'
mod 'repository', '2.2.0', :github_tarball => 'boxen/puppet-repository'
